batch_size: 8
data_dim: 110
epochs: 50
learning_rate: 0.0001
mask_ratio: 0.5
max_sequence_length: 256
model_name: small
positional_encoding: learnable_normal-0.08
optimizer: adamw
scheduler: cos
seed: 0
num_workers: 2