method: grid
metric:
  goal: maximize
  name: val_accuracy
name: classification_hyperparameters-1
parameters:
  learning_rate:
    values:
      - 0.0001
      - 0.00001
  batch_size:
    values:
      - 8
      - 16
      - 32
  scheduler:
    values:
      - cos
      - step
  epochs:
    values:
      - 100
      - 150
