method: grid
metric:
  goal: maximize
  name: val_accuracy
name: classification_hyperparameters-0
parameters:
  learning_rate:
    values:
      - 0.0001
      - 0.001
  batch_size:
    values:
      - 4
      - 8
      - 16
  scheduler:
    values:
      - none
      - cos
      - step
  epochs:
    values:
      - 50
      - 100
